TAG_PHASE_VARS  = "vars"
TAG_PHASE_COND  = "cond"
TAG_PHASE_SUBST = "subst"
TAG_PHASE_EXTS  = "exts"
TAG_PHASE_TARG  = "targ"
TAG_PHASE_CONV  = "conv"
TAG_PHASE_ATTR  = "attr"
TAG_PHASE_PRE   = "pre"
TAG_PHASE_CODE  = "code"
TAG_PHASE_POST  = "post"
TAG_PHASE_SHOW  = "show"
TAG_PHASE_FIN   = "fin"


TAG_PHASES_ORDER = [
    TAG_PHASE_VARS,
    TAG_PHASE_COND,
    TAG_PHASE_SUBST,
    TAG_PHASE_EXTS,
    TAG_PHASE_TARG,
    TAG_PHASE_CONV,
    TAG_PHASE_ATTR,
    TAG_PHASE_PRE,
    TAG_PHASE_CODE,
    TAG_PHASE_POST,
    TAG_PHASE_SHOW,
    TAG_PHASE_FIN,
]
